[project]
name = "ai-lab-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sandeep-singh-99", email = "sandeep.necoder@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.3.16",
    "streamlit>=1.62.0",
]

[project.scripts]
ai-lab-projects = "ai_lab_projects:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
